<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{cholBatch}
-->


## Chol
```{r package}
#library(Matrix)

```


```{r cpu_function}
a1 = matrix(c(25,15,-5,15,18,0,-5,0,11),nrow=3,ncol=3,byrow=TRUE)
x <- chol(a1)   ## start from factor given by chol
y <- diag(x)   ## extract sqrt(D)
L1 <- t(x/y)     ## get unit lower triangular factor
D1 <- diag(x^2)  ## and diagonal


a2 = matrix(c(2,5,-5,5,16,3,-5,3,85),nrow=3,ncol=3, byrow=TRUE)
x <- chol(a2)   ## start from factor given by chol
y <- diag(x)   ## extract sqrt(D)
L2 <- t(x/y)     ## get unit lower triangular factor
D2 <- diag(x^2)  ## and diagonal


A1 = cbind(c(0,0,0,0), rbind(c(0,0,0),a1))  #4x4
A2 = cbind(c(0,0,0,0), rbind(c(0,0,0),a2))

rbind(A1,A2)
L1;D1;L2;D2
```

```{r chol_two_batch}
library(gpuBatchMatrix)
library(gpuR)
gpuA<-vclMatrix(rbind(A1,A2),type="float")
diagMat = vclMatrix(0, 3, ncol(A1), type = "float")
NglobalChol =  c(4,4,1)
NlocalChol = c(2,4,1)
NlocalCache = 100
gpuBatchMatrix:::cholBatchBackend(gpuA, diagMat, c(1,3,1,3), c(1,2,0,3), 2L,
                             NglobalChol, NlocalChol, NlocalCache)

as.matrix(gpuA)
as.matrix(diagMat)



library(gpuBatchMatrix)
library(gpuR)
gpuA<-vclMatrix(rbind(A1,A2),type="double")
diagMat = vclMatrix(0, 3, ncol(A1), type = "double")
NglobalChol =  c(4,4,1)
NlocalChol = c(2,4,1)
NlocalCache = 100
gpuBatchMatrix:::cholBatchBackend(gpuA, diagMat, c(1,3,1,3), c(1,2,0,3), 2L,
                             NglobalChol, NlocalChol, NlocalCache)

as.matrix(gpuA)
as.matrix(diagMat)
```


```{r chol_R_function}
rbind(a1,a2)
a<-vclMatrix(rbind(a1,a2),type="float")
diagMat = vclMatrix(0, 2, ncol(a1), type = "float")
result<-gpuBatchMatrix::cholBatch(a, diagMat, numbatchD=2L,
                             Nglobal=NglobalChol, Nlocal=NlocalChol, NlocalCache=NlocalCache)

L1;D1;L2;D2
as.matrix(a)
as.matrix(diagMat)
```






```{r problemexampleSep14, eval=F}
# this file used for the example on paper
library("gpuR")
library("gpuBatchMatrix")
library('geostatsp')
Ngrid = c(40, 40)
NlocalCache = 1000
Nglobal = c(64L, 64L, 16L)
Nlocal = c(4L, 2L, 2L)
theType = "double"



myRaster = raster(
  extent(0,Ngrid[1]/Ngrid[2],5,6),
  Ngrid[2], Ngrid[1]
)


coordsSp = sp::SpatialPoints(xyFromCell(myRaster, 1:ncell(myRaster)))
coordsGpu = vclMatrix(coordsSp@coords, 
                      nrow(coordsSp@coords), 
                      ncol(coordsSp@coords), type=theType)
#dist(coordsSp@coords)
myParamsBatch = 
  rbind(c(shape=1.25, range=0.5, variance = 1.5, nugget = 0,anisoRatio = 1, anisoAngleRadians = 0),
        c(shape=2.15, range=0.25, variance = 2, nugget = 0, anisoRatio = 4, anisoAngleRadians = pi/7),
        c(shape=0.55, range=1.5, variance = 2, nugget = 0, anisoRatio = 4, anisoAngleRadians = pi/7),
        c(shape=2.15, range=0.5, variance = 2, nugget = 0, anisoRatio = 4, anisoAngleRadians = -pi/7),
        c(shape=2.15, range=0.5, variance = 2, nugget = 0, anisoRatio = 2, anisoAngleRadians = pi/4))

myParamsBatch = myParamsBatch[rep(1,8),]

paramsGpu = gpuBatchMatrix::maternGpuParam(myParamsBatch, type=theType)
myParamsBatch = t(apply(myParamsBatch, 1, geostatsp::fillParam))
myParamsBatch = cbind(myParamsBatch, matrix(0, nrow(myParamsBatch), 22-ncol(myParamsBatch)))

maternCov = vclMatrix(0, nrow(paramsGpu)*nrow(coordsGpu), nrow(coordsGpu),type=theType)
dim(maternCov)
gpuBatchMatrix::maternBatch(maternCov, coordsGpu, paramsGpu, Nglobal=c(128,64,16), Nlocal=c(4,4,4))

set=3
var4cpu = geostatsp::matern(
  x=coordsSp,
  param=drop(myParamsBatch[set,1:7])
)
dim(var4cpu)

a<-prod(Ngrid)*(set-1)+1
b<-prod(Ngrid)*set
var4gpu = maternCov[c(a:b), ]
range(var4gpu-var4cpu)


###########################################################################################################
diagMat = vclMatrix(0, nrow(paramsGpu), ncol(maternCov), type = theType)
outputChol = deepcopy(maternCov)
gpuBatchMatrix::cholBatch(outputChol, diagMat, numbatchD=nrow(myParamsBatch), Nglobal = c(64,16,1), Nlocal = c(4,16,1),NlocalCache = 1000)
dim(outputChol)

cholCpu = as.matrix((chol(var4cpu)))            #cholCpu[1:6,1:6]
theDiag = diag(cholCpu)
cholCpu = cholCpu %*% diag(1/theDiag)
theDiag = theDiag^2


chol4gpu = outputChol[a:b, ]
chol4gpu[upper.tri(chol4gpu)] = 0
diag(chol4gpu) = 1

range(cholCpu - chol4gpu)
range(theDiag - as.matrix(diagMat)[set,])




```









