<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{crossprodBatch}
-->


```{r setup, include=FALSE}
library('gpuR')
```


```{r crossprod_test10.10}
library("gpuR")
library("gpuBatchMatrix")
nrow = 20
ncol=5
A = matrix(0.01*sample(100, nrow*ncol, replace=TRUE),
           nrow, ncol, byrow = TRUE) 


D1 = matrix(0,nrow=nrow, ncol=nrow, byrow = TRUE) 
diag(D1)<-sample(100, nrow, replace=TRUE)

C = matrix(0, nrow=ncol, ncol=ncol)


Nparam = 8
bigA <- do.call(rbind, replicate(Nparam, A, simplify=FALSE))
bigD <- do.call(rbind, replicate(Nparam, diag(D1), simplify = FALSE))
bigC <- do.call(rbind, replicate(Nparam, C, simplify=FALSE))


gpuA = vclMatrix(bigA, type='double'); dim(gpuA)
gpuD = vclMatrix(bigD, type='double')
gpuC = vclMatrix(bigC, type='double')

#C = D1^(-1) B
realC = t(A)%*% solve(D1) %*%A
realC[upper.tri(realC)] <- 0
cpuC = do.call(rbind, replicate(Nparam, realC, simplify=FALSE))

gpuBatchMatrix::crossprodBatch(gpuC, 
                          gpuA, 
                          gpuD,
                          invertD = TRUE,
                          Nglobal = c(64, 64,2), 
                          Nlocal =  c(8,4,1),
                          NlocalCache = 1000)

range(as.matrix(gpuC)-cpuC)

```


```{r crossprodbatch_more, eval=F}
library("gpuR")
library("gpuBatchMatrix")


D1 <- matrix(0,nrow=5, ncol=5)
diag(D1)<-c(1,2,3,4,30)
D1
#a = matrix(c(1,0,0,0,1,0,0,0,1,1,0,0,0,1,0),nrow=5,ncol=3, byrow=T)
a = matrix(rep(1,15),nrow=5,ncol=3, byrow=T)
a
result<- t(a)%*% D1%*%a
result     # 3x3
D2 <- matrix(0,nrow=5, ncol=5)
diag(D2)<-c(10.6,1,1,1, 1)
#D2
result2<- t(a)%*% D2%*%a
result2

gpuC<-vclMatrix(0, nrow=24, ncol=3,type="float")   
gpuA<-vclMatrix(rbind(a,a,a,a,a,a,a,a),type="float")
gpuD<-vclMatrix(rbind(diag(D1),diag(D2),diag(D1),diag(D2),diag(D1),diag(D2),diag(D1),diag(D2)), nrow=8,ncol=nrow(D2),type='float')

gpuBatchMatrix::crossprodBatch(gpuC, 
                          gpuA,
                          gpuD,
                          invertD = FALSE,
                          Nglobal = c(64, 64), 
                          Nlocal =  c(4, 32),
                          NlocalCache = 1000)

as.matrix(gpuC)

```


```{r checkAug26, eval=FALSE}
library("gpuR")
library("gpuBatchMatrix")


D1 <- matrix(0,nrow=5, ncol=5)
diag(D1)<-c(1,2,3,1,3)
D1
#a = matrix(c(1,0,0,0,1,0,0,0,1,1,0,0,0,1,0),nrow=5,ncol=3, byrow=T)
a = matrix(sample(50, 15, replace=TRUE),nrow=5,ncol=3, byrow=T)
a
result<- t(a)%*% D1%*%a
     # 3x3
D2 <- matrix(0,nrow=5, ncol=5)
diag(D2)<-c(2,1,3,1, 2)
#D2
result2<- t(a)%*% D2%*%a
result
result2

gpuC<-vclMatrix(0, nrow=24, ncol=3,type="double")   
gpuA<-vclMatrix(rbind(a,a,a,a,a,a,a,a),type="double")
gpuD<-vclMatrix(rbind(diag(D1),diag(D2),diag(D1),diag(D2),diag(D1),diag(D2),diag(D1),diag(D2)), nrow=8,ncol=nrow(D2),type='double')

gpuBatchMatrix::crossprodBatch(gpuC, 
                          gpuA,
                          gpuD,
                          invertD = FALSE,
                          Nglobal = c(64, 64), 
                          Nlocal =  c(4, 32),
                          NlocalCache = 100)

as.matrix(gpuC)

```


